export enum ExtentionSelector {
	pageError = '#extention-page-error',
	button = '#extention-button',
	pageState = '#extention-page-state',
	info = '#extention-page-info',
	body = '#extention-body',
	paginationTop = '.pagination-top',
	paginationBottom = '.pagination-bottom',
	paginationEl = '.pagination-el',
	contentEl = '.content',
	paginationTopСhild = '.pagination-top-child',
	settingsButtion = '#extention-settings-button',
	settingsArea = '#extention-settings',
	startMessage = '.start_message',
	settingsClose = '#extention-settings-close',
	context = '#context-textarea',
	saveKey = '#save-key',
	firstAddKey = '#first-add-key',
	addKeyArea = `#extention-add-key`,
	extensionLanguage = '#extensionLanguage',
	responseLanguage = `#responseLanguage`,
	setApiSettings = `#setApiSettings`,
	saveSettings = '#save-settings',
}
