export enum ExtensionSelector {
	pageError = '#extension-page-error',
	button = '#extension-button',
	pageState = '#extension-page-state',
	info = '#extension-page-info',
	body = '#extension-body',
	paginationTop = '.pagination-top',
	paginationBottom = '.pagination-bottom',
	paginationEl = '.pagination-el',
	contentEl = '.content',
	paginationTopChilde = '.pagination-top-child',
	settingsButton = '#extension-settings-button',
	settingsArea = '#extension-settings',
	startMessage = '.start_message',
	settingsClose = '#extension-settings-close',
	context = '#context-textarea',
	saveKey = '#save-key',
	firstAddKey = '#first-add-key',
	addKeyArea = `#extension-add-key`,
	extensionLanguage = '#extensionLanguage',
	responseLanguage = `#responseLanguage`,
	setApiSettings = `#setApiSettings`,
	saveSettings = '#save-settings',
}
